/*
   Copyright 2019 Dmitry Kolmakov

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

#pragma once

#include <string>

const char const_configuration[] =
    "\t"
    "# Create history manager home directory"
    "\n"
    "\t"
    "mkdir -p $hm_home"
    "\n"
    "\n"
    "\t"
    "# Path to the HM database"
    "\n"
    "\t"
    "hm_history_db=$hm_home/history.db"
    "\n"
    "\n"
    "\t"
    "# Path to the temporary history file"
    "\n"
    "\t"
    "hm_history_tmp=$hm_home/history.tmp"
    "\n"
    "\n"
    "\t"
    "# Create a new session entry in the database corresponding to the current "
    "terminal session"
    "\n"
    "\t"
    "hm_session_id=$(hm-db $hm_history_db session)"
    "\n"
    "\n"
    "\t"
    "# Service string to split values of stored commands"
    "\n"
    "\t"
    "separator=\"!!hmseparator!!\"\n"
    "\n"
    "\t"
    "# Set a script to be executed after each other command in the current "
    "terminal session"
    "\n"
    "\t"
    "prompt_command() {"
    "\n"
    "\t\t"
    "rc=$?;"
    "\n"
    "\t\t"
    "if [ $(id -u) -ne 0 ] && ! [ -z $hm_session_id ];"
    "\n"
    "\t\t"
    "then"
    "\n"
    "\t\t\t"
    "echo ${hm_session_id}${separator}$(date +\"%Y-%m-%d "
    "%H:%M:%S\")${separator}$(pwd)${separator}\"$(hm_extract_last_cmd)\"${"
    "separator}$rc >> $hm_history_tmp;"
    "\n"
    "\t\t"
    "fi"
    "\n"
    "\t"
    "}"
    "\n"
    "\n"
    "\t"
    "# Wrapper for hm-db which adds the selected commands at the beginning of "
    "the current terminal history"
    "\n"
    "\t"
    "hm() {"
    "\n"
    "\t\t"
    "# Parse arguments"
    "\n"
    "\t\t"
    "ARGS="
    "\n"
    "\t\t"
    "for i in \"$@\"\n"
    "\t\t"
    "do "
    "\n"
    "\t\t"
    "case $i in "
    "\n"
    "\t\t\t"
    "-v|--version)"
    "\n"
    "\t\t\t"
    "hm-db --version"
    "\n"
    "\t\t\t"
    ";;"
    "\n"
    "\t\t\t"
    "-h|--help)"
    "\n"
    "\t\t\t"
    "hm-db --wrapped-help"
    "\n"
    "\t\t\t"
    ";;"
    "\n"
    "\t\t\t"
    "-i|--info)"
    "\n"
    "\t\t\t"
    "hm-db $hm_history_db info $hm_session_id"
    "\n"
    "\t\t\t"
    ";;"
    "\n"
    "\t\t\t"
    "*)"
    "\n"
    "\t\t\t"
    "ARGS=\"$ARGS $i\"\n"
    "\t\t\t"
    ";;"
    "\n"
    "\t\t"
    "esac"
    "\n"
    "\t\t"
    "done"
    "\n"
    "\n"
    "\t\t"
    "# Perform history recovery"
    "\n"
    "\t\t"
    "if ! [ -z \"$ARGS\" ]"
    "\n"
    "\t\t"
    "then"
    "\n"
    "\t\t\t"
    "TMPFILE=$(mktemp extracted_history.XXXXXXXXXX)"
    "\n"
    "\t\t\t"
    "# Parse commands saved to the text file"
    "\n"
    "\t\t\t"
    "hm-db $hm_history_db parse $hm_history_tmp $separator"
    "\n"
    "\t\t\t"
    "# Update history"
    "\n"
    "\t\t\t"
    "hm-db $hm_history_db select $hm_session_id $(echo $ARGS) > $TMPFILE && "
    "echo hm \"$*\" >> $TMPFILE && hm_load_history $TMPFILE"
    "\n"
    "\t\t\t"
    "if [ $? -eq 0 ]; then echo \"History successfully updated!\"; fi"
    "\n"
    "\t\t\t"
    "rm -rf $hm_history_tmp $TMPFILE"
    "\n"
    "\t\t"
    "fi"
    "\n"
    "\t"
    "}"
    "\n"
    "\n"
    "\t"
    "if [ $ZSH_VERSION ]"
    "\n"
    "\t"
    "then"
    "\n"
    "\t\t"
    "hm_load_history() {"
    "\n"
    "\t\t\t"
    "fc -R $1"
    "\n"
    "\t\t\t"
    "fc -W"
    "\n"
    "\t\t"
    "}"
    "\n"
    "\t\t"
    "hm_extract_last_cmd() {"
    "\n"
    "\t\t\t"
    "echo $(fc -ln -1)"
    "\n"
    "\t\t"
    "}"
    "\n"
    "\t\t"
    "precmd_functions=(${precmd_functions} prompt_command)"
    "\n"
    "\t"
    "fi"
    "\n"
    "\n"
    "\t"
    "if [ $BASH_VERSION ]"
    "\n"
    "\t"
    "then"
    "\n"
    "\t\t"
    "hm_load_history() { "
    "\n"
    "\t\t\t"
    "SAVE_HISTFILE=$HISTFILE"
    "\n"
    "\t\t\t"
    "HISTFILE=$1"
    "\n"
    "\t\t\t"
    "history -r"
    "\n"
    "\t\t\t"
    "HISTFILE=$SAVE_HISTFILE"
    "\n"
    "\t\t\t"
    "history -w"
    "\n"
    "\t\t"
    "}"
    "\n"
    "\t\t"
    "hm_extract_last_cmd() {"
    "\n"
    "\t\t\t"
    "history 1 | sed -E \"s/^ *[0-9]* *//\"\n"
    "\t\t"
    "}"
    "\n"
    "\t\t"
    "export PROMPT_COMMAND='prompt_command;'$PROMPT_COMMAND"
    "\n"
    "\t"
    "fi"
    "\n";
